name: Data Ingestion & Processing

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      MY_BUCKET: ${{ secrets.MY_BUCKET }}
      CHEMIN_FICHIER: "data/price_of_healthy_diet_clean.csv"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run Ingestion (Kaggle -> S3)
        run: |
          uv run --with click --with duckdb --with kagglehub --with python-dotenv \
          python src/data/ingest_data.py

      - name: Run Processing (S3 CSV -> S3 Parquet -> Local Parquet)
        run: |
          uv run --with click --with duckdb --with python-dotenv \
          python src/data/data_preprocessing.py "s3://${{ env.MY_BUCKET }}/${{ env.CHEMIN_FICHIER }}" 
